services:
  evmqtt:
    hostname: evmqtt
    container_name: evmqtt
    image: odtdock/evmqtt
    restart: unless-stopped
    volumes:
      - "./config.json:/data/config.json:ro"
      - "/dev/input:/dev/input:ro"
      #- "/usr/local/share/ca-certificates/custom-ca/root.crt:/etc/ssl/certs/ca-certificates.crt"
    environment:
      TZ: Europe/Stockholm
    devices:
      - /dev/input/event4
